[package]
name = "evian-tracking"
description = "Robot localization and tracking algorithms in evian."
repository = "https://github.com/vexide/evian/"
authors = ["Tropical"]
license = "MIT"
categories = ["science::robotics", "no-std", "mathematics", "embedded"]
keywords = ["vex", "vexide", "vex-robotics", "robotics", "autonomous"]
version = "0.0.1-rc.1"
edition = "2024"

[dependencies]
vexide = { workspace = true }
evian-math = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["armv7a-none-eabi"]